//
//  CountryPickerInterfaces.swift
//  Auth
//
//  Created by Adam Cseke on 2022. 02. 22..
//  Copyright (c) 2022. levivig. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

protocol CountryPickerWireframeInterface: WireframeInterface {
    func dismissCountryPicker(country: String, flag: String)
}

protocol CountryPickerViewInterface: ViewInterface {
}

protocol CountryPickerPresenterInterface: PresenterInterface {
    func didSelectCountry(country: String, flag: String)
}

protocol CountryPickerInteractorInterface: InteractorInterface {
}
