//
//  CountryPickerInteractor.swift
//  Auth
//
//  Created by Adam Cseke on 2022. 02. 22..
//  Copyright (c) 2022. levivig. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation

final class CountryPickerInteractor {
}

// MARK: - Extensions -

extension CountryPickerInteractor: CountryPickerInteractorInterface {
}
