//
//  CountryPickerPresenter.swift
//  Auth
//
//  Created by Adam Cseke on 2022. 02. 22..
//  Copyright (c) 2022. levivig. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation

final class CountryPickerPresenter {

    // MARK: - Private properties -

    private unowned let view: CountryPickerViewInterface
    private let interactor: CountryPickerInteractorInterface
    private let wireframe: CountryPickerWireframeInterface
    
    private var flag: String = ""
    private var country: String = ""

    // MARK: - Lifecycle -

    init(
        view: CountryPickerViewInterface,
        interactor: CountryPickerInteractorInterface,
        wireframe: CountryPickerWireframeInterface
    ) {
        self.view = view
        self.interactor = interactor
        self.wireframe = wireframe
    }
    
    func viewDidLoad() {
        
    }
}

// MARK: - Extensions -

extension CountryPickerPresenter: CountryPickerPresenterInterface {
    func didSelectCountry(country: String, flag: String) {
        wireframe.dismissCountryPicker(country: country, flag: flag)
    }

}
