//
//  HomePresenter.swift
//  Auth
//
//  Created by Adam Cseke on 2022. 02. 18..
//  Copyright (c) 2022. levivig. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation

final class HomePresenter {

    // MARK: - Private properties -

    private unowned let view: HomeViewInterface
    private let interactor: HomeInteractorInterface
    private let wireframe: HomeWireframeInterface
    
    private var country: String = ""
    private var currentInput: String = ""
    private var flag: String = ""

    // MARK: - Lifecycle -

    init(
        view: HomeViewInterface,
        interactor: HomeInteractorInterface,
        wireframe: HomeWireframeInterface,
        country: String,
        flag: String
    ) {
        self.view = view
        self.interactor = interactor
        self.wireframe = wireframe
        self.country = country
        self.flag = flag
    }
    
    func viewDidLoad() {
        view.setCountry(country: self.country, flag: self.flag)
    }
}

// MARK: - Extensions -

extension HomePresenter: HomePresenterInterface {
    func goToVerification() {
        wireframe.goToVerification(phoneNumber: self.currentInput)
    }
    
    func goToLogin() {
        wireframe.goToLogin()
    }
    
    func inputChanged(text: String) {
        
        self.currentInput = text
        
        view.setButton(enable: text.count > 8)
    }
    
    func countryPickerButtonTapped() {
        wireframe.goToCountryPicker(delegate: self)
    }
    
    func nextButtonTapped() {
        if let stored = KeychainManager.shared.get(account: self.currentInput) {
            goToLogin()
        } else {
            goToVerification()
        }
    }
}

extension HomePresenter: HomeDelegate {
    func countrySelected(country: String, flag: String) {
        view.setCountry(country: country, flag: flag)
    }
}
