//
//  HomeViewController.swift
//  Auth
//
//  Created by Adam Cseke on 2022. 02. 18..
//  Copyright (c) 2022. levivig. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class HomeViewController: BaseViewController {
    
    private var titleLabel: UILabel!
    private var descriptionLabel: UILabel!
    private var phoneNumberTextField: PhoneNumberTextField!
    private var nextButton: Button!
    private var countryPickerButton: UIButton!
    private var downArrowImageView: UIImageView!
    private var country: String?
    private var countryCount: Int? = 0
    private var countryFlag: String = ""
    
    private var phoneNumber: String?
    private var savedPhoneNumber: String?
    
    // MARK: - Public properties -
    var presenter: HomePresenterInterface!
    
    // MARK: - Lifecycle -
    
    override func viewDidLoad() {
        super.viewDidLoad()
        setup()
    }
    
    private func setup() {
        configureViewController()
        configureTitleLabel()
        configureDescriptionLabel()
        configurePhoneNumberTextfield()
        configureCountryPickerButton()
        configureDownArrowImageView()
        configureButton()
        self.hideKeyboardWhenTappedAround()
        NotificationCenter.default.addObserver(self, selector: #selector(keyboardWillShow), name: UIResponder.keyboardWillShowNotification, object: nil)
        NotificationCenter.default.addObserver(self, selector: #selector(keyboardWillHide), name: UIResponder.keyboardWillHideNotification, object: nil)
    }
    
    private func configureViewController() {
        view.backgroundColor = Colors.background
    }
    
    private func configureTitleLabel() {
        titleLabel = UILabel()
        titleLabel.text = "HomeViewController.TitleLabel".localized
        titleLabel.textColor = Colors.blackLabel
        titleLabel.textAlignment = .center
        titleLabel.font = UIFont(name: "Hind-Bold", size: 24)
        view.addSubview(titleLabel)
        
        titleLabel.snp.makeConstraints { make in
            make.centerY.equalToSuperview().multipliedBy(0.53)
            make.leading.equalToSuperview()
            make.centerX.equalToSuperview()
        }
    }
    
    private func configureDescriptionLabel() {
        descriptionLabel = UILabel()
        descriptionLabel.text = "HomeViewController.DescriptionLabel".localized
        descriptionLabel.textColor = Colors.blackLabel
        descriptionLabel.numberOfLines = 5
        descriptionLabel.textAlignment = .center
        descriptionLabel.font = UIFont(name: "Hind-Regular", size: 15)
        view.addSubview(descriptionLabel)
        
        descriptionLabel.snp.makeConstraints { make in
            make.top.equalTo(titleLabel.snp.bottom).offset(10)
            make.leading.equalToSuperview().offset(32)
            make.centerX.equalToSuperview()
        }
    }
    
    private func configurePhoneNumberTextfield() {
        phoneNumberTextField = PhoneNumberTextField()
        phoneNumberTextField.customDelegate = self
        phoneNumberTextField.delegate = self
        phoneNumberTextField.textAlignment = .left
        phoneNumberTextField.placeholder = "HomeViewController.TextField.Registration".localized
        phoneNumberTextField.keyboardType = .numberPad
        phoneNumberTextField.backgroundColor = .white
        phoneNumberTextField.layer.cornerRadius = 11
        
        view.addSubview(phoneNumberTextField)
        
        phoneNumberTextField.snp.makeConstraints { make in
            make.top.equalTo(descriptionLabel.snp.bottom).offset(32)
            make.centerX.equalToSuperview()
            make.leading.equalToSuperview()
            make.height.equalTo(50)
        }
    }
    
    private func configureCountryPickerButton() {
        countryPickerButton = UIButton(type: .custom)
        countryPickerButton.addTarget(self, action: #selector(didTapCountryPickerButton), for: .touchUpInside)
        
//        let countryFlag = NSTextAttachment()
//        countryFlag.image = UIImage(systemName: "countryFlag")
//        let countryFlagImageString = NSMutableAttributedString(attachment: countryFlag)
        
        countryPickerButton.setTitle("📍", for: .normal)
        
        view.addSubview(countryPickerButton)
        
        countryPickerButton.snp.makeConstraints { make in
            make.centerY.equalTo(phoneNumberTextField.snp.centerY)
            make.leading.equalTo(phoneNumberTextField.snp.leading).offset(16)
            make.height.width.equalTo(28)
        }
    }
    
    @objc private func didTapCountryPickerButton() {
        presenter.countryPickerButtonTapped()
    }
    
    private func configureDownArrowImageView() {
        downArrowImageView = UIImageView()
        downArrowImageView.image = UIImage(systemName: "chevron.down")
        downArrowImageView.tintColor = Colors.downArrow
        view.addSubview(downArrowImageView)
        
        downArrowImageView.snp.makeConstraints { make in
            make.centerY.equalTo(phoneNumberTextField.snp.centerY)
            make.leading.equalTo(countryPickerButton.snp.trailing).offset(4)
        }
    }
    
    private func configureButton() {
        nextButton = Button()
        nextButton.bind( buttonLabelText: "HomeViewController.ButtonTitle".localized,
                         font: UIFont(name: "Hind-Bold", size: 16) ?? UIFont(),
                         textColor: .white)
        nextButton.addTarget(self, action: #selector(nextButtonTapped), for: .touchUpInside)
        
        view.addSubview(nextButton)
        
        nextButton.snp.makeConstraints { make in
            make.top.equalTo(phoneNumberTextField.snp.bottom).offset(32)
            make.centerX.equalToSuperview()
            make.leading.equalToSuperview().offset(15)
            make.height.equalTo(50)
        }
    }
    
    @objc private func nextButtonTapped() {
        if let savedUserData = UserDefaults.standard.object(forKey: "user") as? Data {
            let decoder = JSONDecoder()
            if let savedUser = try? decoder.decode(User.self, from: savedUserData) {
                self.savedPhoneNumber = savedUser.phoneNumber
            }
        }
        if self.phoneNumber == self.savedPhoneNumber {
            presenter.goToLogin()
        } else {
            presenter.goToVerification()
        }
    }
}

// MARK: - Extensions -

extension HomeViewController: HomeViewInterface {
    func setCountry(country: String, flag: String) {
        phoneNumberTextField.text?.removeAll()
        phoneNumberTextField.text?.append(country)
        countryCount = country.count
        let selectedCountryFlag = CountryCodes.flag(country: flag).decodeEmoji
        countryPickerButton.setTitle(selectedCountryFlag, for: .normal)
        print(country)
        print(countryFlag.decodeEmoji)
    }
    
    func setButton(enable: Bool) {
        if !enable {
            nextButton.backgroundColor = Colors.button.withAlphaComponent(0.5)
            nextButton.isEnabled = false
        } else {
            nextButton.backgroundColor = Colors.button
            nextButton.isEnabled = true
        }
    }
    
    @objc func keyboardWillShow(notification: NSNotification) {
        if let keyboardSize = (notification.userInfo?[UIResponder.keyboardFrameEndUserInfoKey] as? NSValue)?.cgRectValue {
            if self.view.frame.origin.y == 0 {
                self.view.frame.origin.y -= keyboardSize.height * 0.30
            }
        }
    }
    
    @objc func keyboardWillHide(notification: NSNotification) {
        if self.view.frame.origin.y != 0 {
            self.view.frame.origin.y = 0
        }
    }
    
}

extension HomeViewController: PhoneNumberTextfieldDelegate {
    
    func textfieldValueDidChange(text: String) {
    }
}

extension HomeViewController: UITextFieldDelegate {
    
    func format(with mask: String, phone: String) -> String {
        let numbers = phone.replacingOccurrences(of: "[^0-9]", with: "", options: .regularExpression)
        var result = ""
        var index = numbers.startIndex // numbers iterator
        
        // iterate over the mask characters until the iterator of numbers ends
        for ch in mask where index < numbers.endIndex {
            if ch == "X" {
                // mask requires a number in this place, so take the next one
                result.append(numbers[index])
                
                // move numbers iterator to the next index
                index = numbers.index(after: index)
                
            } else {
                result.append(ch) // just append a mask character
            }
        }
        return result
    }
    
    func textField(_ textField: UITextField, shouldChangeCharactersIn range: NSRange, replacementString string: String) -> Bool {
        guard let text = textField.text else { return false }
        let newString = (text as NSString).replacingCharacters(in: range, with: string)
        
//        if self.countryCount == 0 {
//            textField.text = format(with: "+XXXXXXXXXXXXXXXX", phone: newString)
//        } else if self.countryCount == 2 {
//            textField.text = format(with: "+X (XX) XXX-XXXX", phone: newString)
//        } else if self.countryCount == 3 {
//            textField.text = format(with: "+XX (XX) XXX-XXXX", phone: newString)
//        } else if self.countryCount == 4 {
//            textField.text = format(with: "+XXX (XX) XXX-XXXX", phone: newString)
//        }
        
        textField.text = format(with: "+XXXXXXXXXXXXXXXX", phone: newString)
        
        presenter.inputChanged(text: textField.text ?? "")
        let phoneNumberValidator = textField.text?.isPhoneNumber
        if phoneNumberValidator == true {
            self.phoneNumber = textField.text ?? ""
        }
        return false
    }
}
