//
//  HomeInterfaces.swift
//  Auth
//
//  Created by Adam Cseke on 2022. 02. 18..
//  Copyright (c) 2022. levivig. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

protocol HomeWireframeInterface: WireframeInterface {
    func goToVerification(phoneNumber: String)
    func goToLogin()
    func goToCountryPicker(delegate: HomeDelegate?)
}

protocol HomeViewInterface: ViewInterface {
    func setButton(enable: Bool)
    func setCountry(country: String, flag: String)
}

protocol HomePresenterInterface: PresenterInterface {
    func goToVerification()
    func goToLogin()
    func countryPickerButtonTapped()
    func inputChanged(text: String)
}

protocol HomeInteractorInterface: InteractorInterface {
}
