//
//  HomeViewController.swift
//  Auth
//
//  Created by Adam Cseke on 2022. 02. 18..
//  Copyright (c) 2022. levivig. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class HomeViewController: BaseViewController {
    
    private var titleLabel: UILabel!
    private var descriptionLabel: UILabel!
    private var phoneNumberTextField: PhoneNumberTextField! {
        didSet {
//            guard let text = phoneNumberTextField.text else { return }
//            phoneNumberTextField.text = text.applyPatternOnNumbers(pattern: "+## (##) ###-####", replacementCharacter: "#")
        }
    }
    private var nextButton: Button!
    private var countryPickerButton: UIButton!
    private var downArrowImageView: UIImageView!
    
    // MARK: - Public properties -
    var presenter: HomePresenterInterface!
    
    // MARK: - Lifecycle -
    
    override func viewDidLoad() {
        super.viewDidLoad()
        setup()
    }
    
    private func setup() {
        configureViewController()
        configureTitleLabel()
        configureDescriptionLabel()
        configurePhoneNumberTextfield()
        configureCountryPickerButton()
        configureDownArrowImageView()
        configureButton()
        self.hideKeyboardWhenTappedAround()
    }
    
    private func configureViewController() {
        view.backgroundColor = Colors.background
    }
    
    private func configureTitleLabel() {
        titleLabel = UILabel()
        titleLabel.text = "HomeViewController.TitleLabel".localized
        titleLabel.textColor = Colors.blackLabel
        titleLabel.textAlignment = .center
        titleLabel.font = .systemFont(ofSize: 24, weight: .bold)
        view.addSubview(titleLabel)
        
        titleLabel.snp.makeConstraints { make in
            make.centerY.equalToSuperview().multipliedBy(0.53)
            make.leading.equalToSuperview()
            make.centerX.equalToSuperview()
        }
    }
    
    private func configureDescriptionLabel() {
        descriptionLabel = UILabel()
        descriptionLabel.text = "HomeViewController.DescriptionLabel".localized
        descriptionLabel.textColor = Colors.blackLabel
        descriptionLabel.numberOfLines = 5
        descriptionLabel.textAlignment = .center
        descriptionLabel.font = .systemFont(ofSize: 15, weight: .regular)
        view.addSubview(descriptionLabel)
        
        descriptionLabel.snp.makeConstraints { make in
            make.top.equalTo(titleLabel.snp.bottom).offset(10)
            make.leading.equalToSuperview().offset(32)
            make.centerX.equalToSuperview()
        }
    }
    
    private func configurePhoneNumberTextfield() {
        phoneNumberTextField = PhoneNumberTextField()
        phoneNumberTextField.customDelegate = self
        phoneNumberTextField.delegate = self
        phoneNumberTextField.textAlignment = .left
        phoneNumberTextField.placeholder = "HomeViewController.TextField.Registration".localized
        phoneNumberTextField.keyboardType = .numberPad
        phoneNumberTextField.backgroundColor = .white
        phoneNumberTextField.layer.cornerRadius = 11
        
        view.addSubview(phoneNumberTextField)
        
        phoneNumberTextField.snp.makeConstraints { make in
            make.top.equalTo(descriptionLabel.snp.bottom).offset(32)
            make.centerX.equalToSuperview()
            make.leading.equalToSuperview().offset(15)
            make.height.equalTo(50)
        }
    }
    
    private func configureCountryPickerButton() {
        countryPickerButton = UIButton(type: .custom)
        countryPickerButton.setImage(UIImage(named: "countryFlag"), for: .normal)
        countryPickerButton.addTarget(self, action: #selector(didTapCountryPickerButton), for: .touchUpInside)
        
        view.addSubview(countryPickerButton)
        
        countryPickerButton.snp.makeConstraints { make in
            make.centerY.equalTo(phoneNumberTextField.snp.centerY)
            make.leading.equalTo(phoneNumberTextField.snp.leading).offset(16)
            make.height.width.equalTo(28)
        }
    }
    
    @objc private func didTapCountryPickerButton() {
        presenter.countryPickerButtonTapped()
    }
    
    private func configureDownArrowImageView() {
        downArrowImageView = UIImageView()
        downArrowImageView.image = UIImage(systemName: "chevron.down")
        downArrowImageView.tintColor = Colors.downArrow
        view.addSubview(downArrowImageView)
        
        downArrowImageView.snp.makeConstraints { make in
            make.centerY.equalTo(phoneNumberTextField.snp.centerY)
            make.leading.equalTo(countryPickerButton.snp.trailing).offset(4)
        }
    }
    
    private func configureButton() {
        nextButton = Button()
        nextButton.bind( buttonLabelText: "HomeViewController.ButtonTitle".localized,
                    font: .systemFont(ofSize: 16, weight: .bold),
                    textColor: .white)
        nextButton.addTarget(self, action: #selector(nextButtonTapped), for: .touchUpInside)
        
        view.addSubview(nextButton)
        
        nextButton.snp.makeConstraints { make in
            make.top.equalTo(phoneNumberTextField.snp.bottom).offset(32)
            make.centerX.equalToSuperview()
            make.leading.equalToSuperview().offset(15)
            make.height.equalTo(50)
        }
    }
    
    @objc
    private func nextButtonTapped() {
        presenter.nextButtonTapped()
    }
}

// MARK: - Extensions -

extension HomeViewController: HomeViewInterface {
    func setCountry(country: String) {
        print(country)
    }
    
    func setButton(enable: Bool) {
        if !enable {
            nextButton.backgroundColor = Colors.button.withAlphaComponent(0.5)
            nextButton.isEnabled = false
        } else {
            nextButton.backgroundColor = Colors.button
            nextButton.isEnabled = true
        }
    }
    
}

extension HomeViewController: PhoneNumberTextfieldDelegate {
    
    func textfieldValueDidChange(text: String) {
        let text = phoneNumberTextField.text ?? ""
        print(text)
    }
}

extension HomeViewController: UITextFieldDelegate {
    
    func format(with mask: String, phone: String) -> String {
        let numbers = phone.replacingOccurrences(of: "[^0-9]", with: "", options: .regularExpression)
        var result = ""
        var index = numbers.startIndex // numbers iterator

        // iterate over the mask characters until the iterator of numbers ends
        for ch in mask where index < numbers.endIndex {
            if ch == "X" {
                // mask requires a number in this place, so take the next one
                result.append(numbers[index])

                // move numbers iterator to the next index
                index = numbers.index(after: index)

            } else {
                result.append(ch) // just append a mask character
            }
        }
        return result
    }

    func textField(_ textField: UITextField, shouldChangeCharactersIn range: NSRange, replacementString string: String) -> Bool {
        guard let text = textField.text else { return false }
        let newString = (text as NSString).replacingCharacters(in: range, with: string)
        textField.text = format(with: "+XX (XX) XXX-XXXX", phone: newString)
        presenter.inputChanged(text: textField.text ?? "")
        
        return false
    }
}
