//
//  HomePresenter.swift
//  Auth
//
//  Created by Adam Cseke on 2022. 02. 18..
//  Copyright (c) 2022. levivig. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation

final class HomePresenter {

    // MARK: - Private properties -

    private unowned let view: HomeViewInterface
    private let interactor: HomeInteractorInterface
    private let wireframe: HomeWireframeInterface
    
    private var country: String = ""
    private var phoneNumber: String = ""
    private var currentInput: String = ""

    // MARK: - Lifecycle -

    init(
        view: HomeViewInterface,
        interactor: HomeInteractorInterface,
        wireframe: HomeWireframeInterface,
        country: String
    ) {
        self.view = view
        self.interactor = interactor
        self.wireframe = wireframe
        self.country = country
    }
    
    func viewDidLoad() {
        view.setCountry(country: self.country)
    }
}

// MARK: - Extensions -

extension HomePresenter: HomePresenterInterface {
    
    func inputChanged(text: String) {
        
        self.currentInput = text
        
        view.setButton(enable: text.count > 8)
    }
    
    func nextButtonTapped() {
        wireframe.goToVerification(phoneNumber: self.currentInput)
    }
    
    func countryPickerButtonTapped() {
        wireframe.goToCountryPicker(delegate: self)
    }
}

extension HomePresenter: HomeDelegate {
    func countrySelected(country: String) {
        view.setCountry(country: country)
    }
}
