//
//  LoginViewController.swift
//  Auth
//
//  Created by Adam Cseke on 2022. 02. 23..
//  Copyright (c) 2022. levivig. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit
import LocalAuthentication

final class LoginViewController: UIViewController {
    
    let localAuthenticationContext = LAContext()
    
    private var phoneNumber: String = "" {
        didSet {
            self.getData()
        }
    }
    private var password: String = ""
    private var errorCode: Int?
    
    private var titleLabel: UILabel!
    private var descriptionLabel: UILabel!
    private var loginTextfield: LoginTextField!
    private var loginButton: Button!
    private var biometricButton: UIButton!
    private var stackView: UIStackView!
    private var incorrectPasswordLabel: UILabel!
    private var forgotPasswordButton: UIButton!
    private var signOutButton: UIButton!
    
    private var changePhoneNumberButton: UIButton!
    
    // MARK: - Public properties -
    
    var presenter: LoginPresenterInterface!
    
    // MARK: - Lifecycle -
    
    override func viewDidLoad() {
        super.viewDidLoad()
        setup()
        presenter.viewDidLoad()
    }
    
    private func setup() {
        configureViewController()
        configureTitleLabel()
        configureDescriptionLabel()
        configureStackView()
        configureLoginTextfield()
        configureLoginButton()
        configureBiometricButton()
        configureIncorrectPassword()
        configureForgotPasswordButton()
        configureSignOutButton()
        self.hideKeyboardWhenTappedAround()
        NotificationCenter.default.addObserver(self, selector: #selector(keyboardWillShow), name: UIResponder.keyboardWillShowNotification, object: nil)
        NotificationCenter.default.addObserver(self, selector: #selector(keyboardWillHide), name: UIResponder.keyboardWillHideNotification, object: nil)
        
        configureChangePhoneNumberButton()
    }
    
    private func configureViewController() {
        view.backgroundColor = Colors.background
    }
    
    private func configureTitleLabel() {
        titleLabel = UILabel()
        titleLabel.text = "LoginViewController.Title.Login".localized
        titleLabel.textColor = Colors.blackLabel
        titleLabel.textAlignment = .center
        titleLabel.font = UIFont(name: "Hind-Bold", size: 24)
        view.addSubview(titleLabel)
        
        titleLabel.snp.makeConstraints { make in
            if UIDevice.Devices.iPhoneSE1stGen {
                make.centerY.equalToSuperview().multipliedBy(0.35)
            } else {
                make.centerY.equalToSuperview().multipliedBy(0.5)
            }
            make.leading.equalToSuperview()
            make.centerX.equalToSuperview()
        }
    }
    
    private func configureDescriptionLabel() {
        descriptionLabel = UILabel()
        descriptionLabel.textColor = Colors.blackLabel
        descriptionLabel.numberOfLines = 5
        descriptionLabel.textAlignment = .center
        descriptionLabel.font = UIFont(name: "Hind-Regular", size: 15)
        view.addSubview(descriptionLabel)
        
        descriptionLabel.snp.makeConstraints { make in
            make.top.equalTo(titleLabel.snp.bottom).offset(10)
            make.leading.equalToSuperview().offset(32)
            make.centerX.equalToSuperview()
        }
    }
    
    private func configureStackView() {
        stackView = UIStackView()
        stackView.alignment = .center
        stackView.axis = .vertical
        stackView.spacing = 15
        stackView.distribution = .fill
        
        view.addSubview(stackView)
        
        stackView.snp.makeConstraints { make in
            make.top.equalTo(descriptionLabel.snp.bottom).offset(15)
            make.leading.equalToSuperview()
            make.centerX.equalToSuperview()
        }
    }
    
    private func configureLoginTextfield() {
        loginTextfield = LoginTextField()
        loginTextfield.textColor = .black
        loginTextfield.backgroundColor = .white
        loginTextfield.layer.cornerRadius = 11
        loginTextfield.isSecureTextEntry = true
        loginTextfield.textAlignment = .center
        loginTextfield.autocapitalizationType = .none
        loginTextfield.customDelegate = self
        loginTextfield.font = UIFont(name: "Hind-Regular", size: 20)
        loginTextfield.addTarget(self, action: #selector(textFieldEdidtingDidChange(_ :)), for: UIControl.Event.editingChanged)
        
        let placeholderAttributes: [NSAttributedString.Key: Any] = [
            NSAttributedString.Key.font: UIFont(name: "Hind-Regular", size: 16),
            NSAttributedString.Key.foregroundColor: Colors.placeholder
        ]
        let attributedPlaceholder = NSMutableAttributedString(string: "LoginViewController.TextField.Placeholder".localized, attributes: placeholderAttributes)
        loginTextfield.attributedPlaceholder = attributedPlaceholder
        
        stackView.addArrangedSubview(loginTextfield)
        
        loginTextfield.snp.makeConstraints { make in
            make.top.equalTo(descriptionLabel.snp.bottom).offset(32)
            make.centerX.equalToSuperview()
            make.leading.equalToSuperview().offset(15)
            make.height.equalTo(50)
        }
    }
    
    @objc func textFieldEdidtingDidChange(_ textField :UITextField) {
        let textAttributes: [NSAttributedString.Key: Any] = [
            NSAttributedString.Key.font: UIFont(name: "Hind-Bold", size: 25),
            NSAttributedString.Key.foregroundColor: Colors.button
        ]
            let attributedString = NSMutableAttributedString(string: loginTextfield.text ?? "", attributes: textAttributes)
            attributedString.addAttribute(NSAttributedString.Key.kern, value: CGFloat(5.0), range: NSRange(location: 0, length: attributedString.length))
            loginTextfield.attributedText = attributedString
        }
    
    private func configureLoginButton() {
        loginButton = Button()
        loginButton.bind( buttonLabelText: "LoginViewController.ButtonTitle".localized,
                          font: UIFont(name: "Hind-Bold", size: 16) ?? UIFont(),
                          textColor: .white)
        loginButton.addTarget(self, action: #selector(loginButtonTapped), for: .touchUpInside)
        
        stackView.addArrangedSubview(loginButton)
        
        loginButton.snp.makeConstraints { make in
            
            make.centerX.equalToSuperview()
            make.leading.equalToSuperview().offset(15)
            make.height.equalTo(50)
        }
    }
    
    @objc private func loginButtonTapped() {
//        self.getData()
        if loginTextfield.text == self.password {
            incorrectPasswordLabel.isHidden = true
            presenter.presentAlert(title: "Successfully logged in", description: "", buttonText: "Yay", alertImage: UIImage(named: "log-in")?.withTintColor(Colors.button) ?? UIImage())
            self.titleLabel.text = "LoginViewController.Title.LoggedIn".localized
            self.signOutButton.isHidden = false
            self.loginButton.isHidden = true
            self.biometricButton.isHidden = true
            self.loginButton.isHidden = true
            self.loginTextfield.isHidden = true
            self.forgotPasswordButton.isHidden = true
            print("Login was successful")
        } else {
            incorrectPasswordLabel.isHidden = false
            print("Login was unsuccessful")
        }
    }
    
    private func configureBiometricButton() {
        biometricButton = UIButton()
        biometricButton.backgroundColor = Colors.button
        biometricButton.layer.cornerRadius = 11
        
        let attributes: [NSAttributedString.Key: Any] = [
            NSAttributedString.Key.font: UIFont(name: "Hind-Regular", size: 16),
            NSAttributedString.Key.foregroundColor: UIColor.white
        ]
        
        let touchID = NSTextAttachment()
        touchID.image = UIImage(systemName: "touchid")?.withTintColor(.white)
        let touchIdImageString = NSMutableAttributedString(attachment: touchID)
        
        let faceID = NSTextAttachment()
        faceID.image = UIImage(systemName: "faceid")?.withTintColor(.white)
        let faceIdImageString = NSMutableAttributedString(attachment: faceID)
        
        var textString = NSAttributedString()
        
        localAuthenticationContext.canEvaluatePolicy(.deviceOwnerAuthenticationWithBiometrics, error: nil)
        
        let biometricType = localAuthenticationContext.biometryType == LABiometryType.faceID ? "Face ID" : "Touch ID"
        print("Supported Biometric type is: \( biometricType )")
        
        if biometricType == "Touch ID" {
            textString = NSAttributedString(string: "LoginViewController.BiometricButton.TouchID".localized, attributes: attributes)
            touchIdImageString.append(textString)
            biometricButton.setAttributedTitle(touchIdImageString, for: .normal)
        } else if biometricType == "Face ID" {
            textString = NSAttributedString(string: "LoginViewController.BiometricButton.FaceID".localized, attributes: attributes)
            faceIdImageString.append(textString)
            biometricButton.setAttributedTitle(faceIdImageString, for: .normal)
        } else {
            biometricButton.isHidden = true
        }
        
        biometricButton.addTarget(self, action: #selector(biometricButtonTapped), for: .touchUpInside)
        
        stackView.addArrangedSubview(biometricButton)
        
        biometricButton.snp.makeConstraints { make in
            make.top.equalTo(loginButton.snp.bottom).offset(16)
            make.centerX.equalToSuperview()
            make.leading.equalToSuperview().offset(15)
            make.height.equalTo(50)
        }
    }
    
    @objc private func biometricButtonTapped() {
        startAuthentication()
    }
    
    private func configureIncorrectPassword() {
        incorrectPasswordLabel = UILabel()
        incorrectPasswordLabel.text = "LoginViewController.IncorrectPassword".localized
        incorrectPasswordLabel.textAlignment = .center
        incorrectPasswordLabel.textColor = Colors.incorrectPassword
        incorrectPasswordLabel.numberOfLines = 2
        incorrectPasswordLabel.isHidden = true
        incorrectPasswordLabel.font = UIFont(name: "Hind-Regular", size: 16)
        
        stackView.addArrangedSubview(incorrectPasswordLabel)
        
        incorrectPasswordLabel.snp.makeConstraints { make in
            make.leading.equalToSuperview().offset(32)
            make.centerX.equalToSuperview()
        }
    }
    
    private func configureForgotPasswordButton() {
        forgotPasswordButton = UIButton()
        forgotPasswordButton.backgroundColor = .clear
        
        stackView.addArrangedSubview(forgotPasswordButton)
        
        let attributes: [NSAttributedString.Key: Any] = [
            NSAttributedString.Key.font: UIFont(name: "Hind-Regular", size: 16),
            NSAttributedString.Key.foregroundColor: UIColor.blue,
            NSAttributedString.Key.underlineStyle: NSUnderlineStyle.single.rawValue
        ]
        
        let attributeString = NSMutableAttributedString(
            string: "LoginViewController.ForgotPassword".localized,
            attributes: attributes
        )
        forgotPasswordButton.setAttributedTitle(attributeString, for: .normal)
        forgotPasswordButton.snp.makeConstraints { make in
            make.leading.equalToSuperview().offset(32)
            make.centerX.equalToSuperview()
        }
    }
    
    @objc func keyboardWillShow(notification: NSNotification) {
            if let keyboardSize = (notification.userInfo?[UIResponder.keyboardFrameEndUserInfoKey] as? NSValue)?.cgRectValue {
                if self.view.frame.origin.y == 0 {
                    self.view.frame.origin.y -= keyboardSize.height * 0.30
                }
            }
        }
        
        @objc func keyboardWillHide(notification: NSNotification) {
            if self.view.frame.origin.y != 0 {
                self.view.frame.origin.y = 0
            }
        }
    
    private func configureSignOutButton() {
        signOutButton = UIButton()
        signOutButton.isHidden = true
        signOutButton.addTarget(self, action: #selector(signOutButtonTapped), for: .touchUpInside)
        
        let attributes: [NSAttributedString.Key: Any] = [
            NSAttributedString.Key.font: UIFont(name: "Hind-Regular", size: 16),
            NSAttributedString.Key.foregroundColor: UIColor.blue,
            NSAttributedString.Key.underlineStyle: NSUnderlineStyle.single.rawValue
          ]
        
        signOutButton.tintColor = Colors.button
        let attributeString = NSMutableAttributedString(
              string: "LoginViewController.SignOut".localized,
              attributes: attributes
            )
        signOutButton.backgroundColor = .clear
        signOutButton.setAttributedTitle(attributeString, for: .normal)
        stackView.addArrangedSubview(signOutButton)
        
        signOutButton.snp.makeConstraints { make in
            make.leading.equalToSuperview().offset(32)
            make.centerX.equalToSuperview()
        }
    }
    
    @objc private func signOutButtonTapped() {
        self.loginTextfield.text = ""
        self.titleLabel.text = "LoginViewController.Title.Login".localized
        self.signOutButton.isHidden = true
        self.loginButton.isHidden = false
        self.biometricButton.isHidden = false
        self.loginButton.isHidden = false
        self.loginTextfield.isHidden = false
        self.forgotPasswordButton.isHidden = false
        self.loginButton.isEnabled = false
    }
    
    private func getData() {
        guard let data = KeychainManager.get(service: "auth.com", account: self.phoneNumber) else {
            print("Failed to read pawwsord")
            return
        }
        let password = String(decoding: data, as: UTF8.self)
        print("Read password: \(password)")
    }
}

// MARK: - Extensions -

extension LoginViewController: LoginViewInterface {
    func setButton(enable: Bool) {
        if !enable {
            loginButton.isEnabled = false
            loginButton.backgroundColor = Colors.button.withAlphaComponent(0.5)
        } else {
            loginButton.isEnabled = true
            loginButton.backgroundColor = Colors.button
        }
    }
    
    func pushPhoneNumber(phoneNumber: String) {
        if let savedUserData = UserDefaults.standard.object(forKey: "user") as? Data {
            let decoder = JSONDecoder()
            if let savedUser = try? decoder.decode(User.self, from: savedUserData) {
                self.phoneNumber = savedUser.phoneNumber
                self.password = savedUser.password
            }
        }
        
        self.getData()
        descriptionLabel.text = "\(self.phoneNumber)"
    }
    
    private func configureChangePhoneNumberButton() {
        changePhoneNumberButton = UIButton()
        changePhoneNumberButton.addTarget(self, action: #selector(changePhoneNumberButtonTapped), for: .touchUpInside)
        
        let attributes: [NSAttributedString.Key: Any] = [
            NSAttributedString.Key.font: UIFont(name: "Hind-Regular", size: 16),
            NSAttributedString.Key.foregroundColor: UIColor.blue,
            NSAttributedString.Key.underlineStyle: NSUnderlineStyle.single.rawValue
        ]
        
        changePhoneNumberButton.tintColor = Colors.button
        let attributeString = NSMutableAttributedString(
            string: "Reset",
            attributes: attributes
        )
        changePhoneNumberButton.backgroundColor = .clear
        changePhoneNumberButton.setAttributedTitle(attributeString, for: .normal)
        view.addSubview(changePhoneNumberButton)
        
        changePhoneNumberButton.snp.makeConstraints { make in
            make.leading.equalToSuperview().offset(10)
            make.bottom.equalToSuperview().offset(-10)
        }
    }
    
    @objc private func changePhoneNumberButtonTapped() {
        presenter.signOutButtonTapped()
    }
    
}

extension LoginViewController: LoginTextFieldDelegate {
    func textfieldValueDidChange(text: String) {
        let text = loginTextfield.text ?? ""
        presenter.inputChanged(text: text)
//        print(text)
    }
}

extension LoginViewController {
    
    func startAuthentication() {
        let contet = LAContext()
        let reason = "Biometric Authntication testing !!"
        var authError: NSError?
        
        if #available(iOS 8.0, macOS 10.12.1, *) {
            if contet.canEvaluatePolicy(.deviceOwnerAuthenticationWithBiometrics, error: &authError) {
                contet.localizedCancelTitle = "Cancel"
                contet.localizedFallbackTitle = "Use Passcode"
                contet.evaluatePolicy(.deviceOwnerAuthenticationWithBiometrics, localizedReason: reason) { success, evaluateError in
                    DispatchQueue.main.async {
                        if success {
                            self.loginTextfield.text = self.password
                            self.loginButtonTapped()
                            print("Login was successful")
                        } else {
                            // User did not authenticate successfully, look at error and take appropriate action
                            print(evaluateError?.localizedDescription)
                        }
                    }
                }
            } else {
                guard let error = authError else {
                    return
                }
                //TODO: Show appropriate alert if biometry/TouchID/FaceID is lockout or not enrolled
                print(self.evaluateAuthenticationPolicyMessageForLA(errorCode: error.code))
                // Could not evaluate policy; look at authError and present an appropriate message to user
                print("Sorry!!.. Could not evaluate policy.\(authError?.localizedDescription)")
            }
        } else {
            print("This feature is not supported.")
        }
    }

    func evaluatePolicyFailErrorMessageForLA(errorCode: Int) -> String {
        var message = ""
        if #available(iOS 11.0, macOS 10.13, *) {
            switch errorCode {
                case LAError.biometryNotAvailable.rawValue:
                    message = "Authentication could not start because the device does not support biometric authentication."

                case LAError.biometryLockout.rawValue:
                    message = "Authentication could not continue because the user has been locked out of biometric authentication, due to failing authentication too many times."

                case LAError.biometryNotEnrolled.rawValue:
                    message = "Authentication could not start because the user has not enrolled in biometric authentication."
                presenter.presentAlert(title: "LoginViewController.AlertViewController.Fingerprint.Title".localized,
                                       description: "LoginViewController.AlertViewController.Fingerprint.Description".localized,
                                       buttonText: "Ok",
                                       alertImage: UIImage(named: "sad")?.withTintColor(Colors.button) ?? UIImage())
                default:
                    message = "Did not find error code on LAError object"
            }
        } else {
            switch errorCode {
                case LAError.touchIDLockout.rawValue:
                    message = "Too many failed attempts."

                case LAError.touchIDNotAvailable.rawValue:
                    message = "TouchID is not available on the device"

                case LAError.touchIDNotEnrolled.rawValue:
                    message = "TouchID is not enrolled on the device"

                default:
                    message = "Did not find error code on LAError object"
            }
        }

        return message;
    }

    func evaluateAuthenticationPolicyMessageForLA(errorCode: Int) -> String {

        var message = ""
        self.errorCode = errorCode
        switch errorCode {

        case LAError.authenticationFailed.rawValue:
            message = "The user failed to provide valid credentials"

        case LAError.appCancel.rawValue:
            message = "Authentication was cancelled by application"

        case LAError.invalidContext.rawValue:
            message = "The context is invalid"

        case LAError.notInteractive.rawValue:
            message = "Not interactive"

        case LAError.passcodeNotSet.rawValue:
            message = "Passcode is not set on the device"

        case LAError.systemCancel.rawValue:
            message = "Authentication was cancelled by the system"

        case LAError.userCancel.rawValue:
            message = "The user did cancel"

        case LAError.userFallback.rawValue:
            message = "The user chose to use the fallback"

        default:
            message = evaluatePolicyFailErrorMessageForLA(errorCode: errorCode)
        }

        return message
    }
}
