//
//  LoginInterfaces.swift
//  Auth
//
//  Created by Adam Cseke on 2022. 02. 23..
//  Copyright (c) 2022. levivig. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

protocol LoginWireframeInterface: WireframeInterface {
    func backToHome()
    func presentAlert(title: String, description: String, buttonText: String, alertImage: UIImage)
}

protocol LoginViewInterface: ViewInterface {
    func pushPhoneNumber(phoneNumber: String)
    func setButton(enable: Bool)
}

protocol LoginPresenterInterface: PresenterInterface {
    func signOutButtonTapped()
    func presentAlert(title: String, description: String, buttonText: String, alertImage: UIImage)
    func inputChanged(text: String)
}

protocol LoginInteractorInterface: InteractorInterface {
}
